---
- name: install mysql windows 
  hosts: vm 
  #become: true
  vars:
     ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
     mysql_package: mysql 
  tasks:
    - name: Install MySQL using Choco
      win_chocolatey: 
        name: "{{ mysql_package }}"
        state: present
